### ISSUE TITLE
The "go to recording" button is not disabled when the app is not connected to the CTM and INS

### ISSUE THREAD

**Issue by yunshufan** [brown-ccv/OmniReferenceClient#105]
@broarr

**Comment by broarr** [comment]
We discussed this in a few meetings. We decided on disabling the record button instead of preventing navigation to the page. Did I miss something?

**Comment by yunshufan** [comment]
Sorry I didn’t make the connection between this feature and that decision. You are right. Please close this issue.

-Yunshu
