### ISSUE TITLE
change name of the app icon

### ISSUE THREAD

**Issue by yunshufan** [brown-ccv/OmniReferenceClient#73]
Is it possible to change the name of the icon? Currently, the front end is called "OmniClient", but inside the app is called "Summit RC+S" and that is how we refer to it with the subjects. This might be confusing to the subjects. @broarr

**Comment by broarr** [comment]
Change these two lines to change the package name:
https://github.com/brown-ccv/OmniReferenceClient/blob/main/package.json#L2-L3
