### ISSUE TITLE
What to do if quit backend by accident. 

### ISSUE THREAD

**Issue by yunshufan** [brown-ccv/OmniReferenceClient#74]
If the subject "x" out the backend, will there be any alert to the subject that something is wrong? And what would be the recommended action that is not too complicated for the subject to do? @broarr

**Comment by broarr** [comment]
You can write some VBS to hide the window when you start the backend. Check this out for reference:

https://keestalkstech.com/2016/07/start-nodejs-app-windowless-windows/#vbs-to-the-rescue

**Comment by broarr** [comment]
Let me know if there's any additional questions

**Comment by broarr** [comment]
Feel free to reopen this ticket with any additional questions or concerns you may have

**Comment by yunshufan** [comment]
I found this way: https://www.cnet.com/how-to/how-to-automatically-start-a-program-minimized-in-windows/
But with these minimized window, there is still a chance to open it by clicking on it. I wonder if there is way to only show it on the task bar, like how dropbox can run in the background.

**Comment by broarr** [comment]
What was wrong with the VBS way of doing it? Did you try it?

**Comment by broarr** [comment]
I've tested the VBS script and it definitely works. Here's the content of my script. The `OmniSummitDeviceService.exe` is the full path to the executable. My script was in the same directory as `OmniSummitDeviceService.exe`

```vbs
CreateObject("Wscript.Shell").Run "OmniSummitDeviceService.exe", 0
```

**Comment by broarr** [comment]
I'm closing the issue again. Give that a shot and tell me how it goes

**Comment by yunshufan** [comment]
This is the vbs script I created: CreateObject("Wscript.Shell").Run "C:\Users\Yunshu Fan\Downloads\Release-20210712T150301Z-001\Release\net472\OmniSummitDeviceService.exe", 0
I try running it, but I got the following error message 
![image](https://user-images.githubusercontent.com/32801111/125986566-439fea81-1777-43ac-8f49-ba4b33b4ef64.png)

**Comment by broarr** [comment]
Let me know if this is OK @yunshufan
